if [ -f ~/.bashrc ];
then
	source ~/.bashrc
fi
##
# Your previous /Users/bushymark/.bash_profile file was backed up as /Users/bushymark/.bash_profile.macports-saved_2009-12-18_at_17:05:23
##

# MacPorts Installer addition on 2009-12-18_at_17:05:23: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

